<?php

namespace OpenCastle\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerGroupRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerGroupRepository extends EntityRepository
{
}
