<?php

namespace OpenCastle\SecurityBundle\Entity;

/**
 * PlayerGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
