<?php

namespace OpenCastle\CoreBundle\Entity;

/**
 * GameEventLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameEventLogRepository extends \Doctrine\ORM\EntityRepository
{
}
