<?php

namespace OpenCastle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use OpenCastle\SecurityBundle\Entity\Player;

/**
 * PlayerStatRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerStatRepository extends EntityRepository
{
    /**
     * @param $shortName
     * @param Player $player
     * @return PlayerStat
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getStatForPlayer($shortName, Player $player)
    {
        $qb = $this->createQueryBuilder('ps')
            ->innerJoin('ps.stat', 's')
            ->where('ps.player = :player')
            ->andWhere('s.shortName = :shortname');

        $qb->setParameter(':player', $player);
        $qb->setParameter(':shortname', $shortName);

        return $qb->getQuery()->getSingleResult();
    }
}
