<?php

namespace OpenCastle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerStatRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerStatRepository extends EntityRepository
{
}
