<?php

namespace OpenCastle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRepository extends EntityRepository
{
}
