<?php

namespace OpenCastle\CoreBundle\Entity;

/**
 * StatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRepository extends \Doctrine\ORM\EntityRepository
{
}
