opencastle_security.connexion:
    path: /login
    defaults: { _controller: OpenCastleSecurityBundle:Security:connexion }
    methods:  [GET, POST]

opencastle_security.connexion_check:
    path: /login_check

opencastle_security.inscription:
    path: /inscription
    defaults: { _controller: OpenCastleSecurityBundle:Security:inscription }
    options:
        expose: true
    methods:  [GET, POST]