services:
    opencastle_security.player_manager:
        class: OpenCastle\SecurityBundle\Security\PlayerManager
        arguments: [@doctrine.orm.entity_manager, @security.encoder_factory]

    opencastle_security.group_manager:
        class: OpenCastle\SecurityBundle\Security\GroupManager
        arguments: [@doctrine.orm.entity_manager]

    opencastle_security.authentication_handler:
        class: OpenCastle\SecurityBundle\Security\AuthenticationHandler
        arguments: [@session, @translator, @event_dispatcher, @opencastle_security.player_connected_event]
        public: false

    opencastle_security.player_connected_event:
        class: OpenCastle\SecurityBundle\GameEvent\PlayerConnectedGameEvent
        arguments: [@security.token_storage, @doctrine.orm.entity_manager]
        tags:
            - { name: opencastle.game_event }