services:
    opencastle_security.player_manager:
        class: OpenCastle\SecurityBundle\Security\PlayerManager
        arguments: [@doctrine.orm.entity_manager, @security.encoder_factory, @mailer, @twig]

    opencastle_security.group_manager:
        class: OpenCastle\SecurityBundle\Security\GroupManager
        arguments: [@doctrine.orm.entity_manager]

    opencastle_security.authentication_handler:
        class: OpenCastle\SecurityBundle\Security\AuthenticationHandler
        public: false