services:
    opencastle_security.player_manager:
        class: OpenCastle\SecurityBundle\Security\PlayerManager
        arguments: [@doctrine.orm.entity_manager, @security.encoder_factory]

    opencastle_security.group_manager:
        class: OpenCastle\SecurityBundle\Security\GroupManager
        arguments: [@doctrine.orm.entity_manager]
