services:
    opencastle_security.player_manager:
        class: OpenCastle\SecurityBundle\Security\PlayerManager
        arguments: [@doctrine, @security.encoder_factory, "@event_dispatcher"]

    opencastle_security.group_manager:
        class: OpenCastle\SecurityBundle\Security\GroupManager
        arguments: [@doctrine]

    opencastle_security.authentication_handler:
        class: OpenCastle\SecurityBundle\Security\AuthenticationHandler
        public: false
